language: elixir
elixir:
  - 1.2.6
cache:
  directories:
    - _build
    - deps
sudo: false
addons:
  postgresql: '9.4' # Use postgres 9.4
before_script:
# Create the test database
- psql -c 'create database chowmonger_test;' -U postgres
