language: elixir
elixir:
  - 1.3.0
cache:
  directories:
    - _build
    - deps
env:
- MIX_ENV=test
sudo: false
addons:
  postgresql: '9.4' # Use postgres 9.4
before_script:
# Create the test database
- psql -c 'create database chowmonger_test;' -U postgres
script: mix coveralls.travis
